#! /usr/bin/env bash

dot="$(cd "$(dirname "$0")"; pwd)"

command="$1"

if [[ "$command" == "--zsh" ]]; then
  $dot/prompt.zsh
fi
if [[ "$command" == "--bash" || "$command" == "" ]]; then
  $dot/prompt.bash
fi
